version: '2.4'

volumes:
  emby-data:
  networks:

services:
  torrent-server:
    image: linuxserver/transmission
    container_name: transmission
    mem_limit: 300m
    env_file: .env
    depends_on:
      - samba
    restart: unless-stopped
    hostname: transmission.local
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=${USERNAME}
      - PASS=${PASSWORD}
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - "./common/data/configs/transmission:/config"
      - ${DATA_LOCATION}/movies:/downloads/complete
      - "./common/data/watch:/watch"
      - "./transmission/temp:/downloads/incomplete"

  samba:
    image: joebiellik/samba-server
    mem_limit: 2048m
    restart: unless-stopped
    env_file: .env
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      # Samba config file
      - "./common/data/configs/samba/smb.conf:/etc/samba/smb.conf"
      # Shares
      - "./common/data/configs:/mnt/configs"
      - ${DATA_LOCATION}/movies:/mnt/movies:ro
      - "./common/data/watch:/mnt/watch:rw"

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    mem_limit: 6144m
    hostname: plex.local
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - PLEX_CLAIM=${PLEXCLAIM}
      - ADVERTISE_IP=http://${IP}:32400/
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - "./common/data/configs/plex:/config"
      - "./plex/temp:/transcode:ro"
      - ${DATA_LOCATION}/movies:/data:rw

  emby:
    init: true
    mem_limit: 6144m
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./emby/Dockerfile
    ports:
      - 8096:8096
      - 8920:8920
    volumes:
      - emby-data:/var/lib/emby
      - ${DATA_LOCATION}/movies:/media/Movies:ro
      - ${DATA_LOCATION}/music:/media/Music:ro
      - ${DATA_LOCATION}/photos:/media/Photos:ro
